# Application Configuration
app:
  name: TransactionTracker
  version: 1.0.0

# Data Path Configuration
paths:
  data: "D:/01_Data/OneDrive/Development/Python/TestData"
  input_dir: "${paths.data}/input/"
  output_dir: "${paths.data}/output/"

# Logging Configuration 
logging:
  level: DEBUG
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  file: "${paths.data}/logs/app.log"

# Parser Configuration
parsers:
  supported_formats:
    - standardchartered
    - journey
  default_parser: standardchartered

# API Configuration 
api:
  gemini_model: "gemini-2.0-pro-exp-02-05"            # gemini-2.0-pro-exp-02-05      gemini-2.0-flash"

# Expense Categorization Configuration
expense_categories:
  Food:
    - Groceries
    - Restaurants
    - Delivery
    - Cafes
  Transportation:
    - Public Transport
    - Taxi
    - Fuel
    - Car Maintenance
  Housing:
    - Rent
    - Utilities
    - Maintenance
    - Furniture
  Entertainment:
    - Movies
    - Subscriptions
    - Games
    - Events
  Shopping:
    - Clothing
    - Electronics
    - Household Items
    - Personal Care
  Health:
    - Medical
    - Pharmacy
    - Insurance
    - Fitness
  Education:
    - Tuition
    - Books
    - Courses
    - Supplies
  Travel:
    - Flights
    - Accommodation
    - Activities
    - Travel Insurance
  Financial:
    - Investments
    - Fees
    - Interest
    - Taxes
  Transfers:
    - Family
    - Friends
    - Self
    - Savings

# PayNow Vendor Mapping
paynow_vendors:
  - vendor: "PAYNOW-GRABFOOD"
    category: "Food"
    subcategory: "Delivery"
  - vendor: "PAYNOW-FAIRPRICE"
    category: "Food"
    subcategory: "Groceries"
  - vendor: "PAYNOW-LAZADA"
    category: "Shopping"
    subcategory: "Household Items"
  - vendor: "PAYNOW-SHOPEE"
    category: "Shopping"
    subcategory: "Household Items"

# External Transactions to Individuals
external_individuals:
  - name: "JOHN DOE"
    category: "Transfers"
    subcategory: "Friends"
  - name: "JANE SMITH"
    category: "Transfers"
    subcategory: "Family"
